adds opentelemetry configs & container
dqualizer/dqualizer pull request #30
Opened 2023-05-24 14:05 UTC by haninator

This adds the configuration for the Opentelemetry Collector, Prometheus and the needed config inside the docker compose file.
This also adds a Prometheus, an Opentelemetry Collector and a Jaeger Container to the docker-compose

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dqualizer/dqualizer/30)

2023-06-01 18:17 UTC, ArianeKraus requested changes

2023-06-01 18:17 UTC, ArianeKraus commented on config/otel-collector-config.yaml
> +    endpoint: :55679
I can think of a use case for using health check but do we have a use case for using pprof and zpages?
If not I would remove both extensions in order to keep the overall configuration at a minimum.

2023-06-01 18:17 UTC, ArianeKraus commented on config/prometheus.yaml
> +      - targets: [ 'otel-collector:8889' ]
Can we add a second scrape endpoint for otel-collector:8888?

2023-06-01 18:17 UTC, ArianeKraus commented on docker-compose.yml
> +      - "14268"
unless we're using it I would suggest to remote 14268 port

2023-06-01 18:17 UTC, ArianeKraus commented on docker-compose.yml
> +      - "1888:1888"   # pprof extension
reminder to remove ports if we end up not using the extensions

2023-06-01 18:17 UTC, ArianeKraus commented on docker-compose.yml
> +      - "4317:4317"   # OTLP gRPC receiver
I would keep the 4317 port internal, as it is currently enough for our use case

2024-01-23 13:17 UTC, ArianeKraus approved these changes

2024-01-23 16:05 UTC, merged

2024-01-23 16:06 UTC, franksn90 reviewed
Full runthrough executed successfully